import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <main>
        <Head>
          <title>Nebraska Creative</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <section>
          <p>
            The Nebraska Creative is your go-to resource for discovering design, advertising, and
            creative agencies in the heart of the Midwest – aka good ol’ Nebraska. With the mindset
            of collaboration over competition, The Nebraska Creative embraces a diverse range of
            creative shops to showcase the assets and skills each has to offer – helping you find
            the perfect team of individuals ready to refresh your business and bring new ideas to
            life. Read about why we created this site.
          </p>
        </section>
      </main>
    </div>
  )
}
