import { Main } from '@modules'
import Section from '@modules/Section'
import H1 from '@typography/H1'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Main>
        <Head>
          <title>Nebraska Creative</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Section id={'landing'}>
          <div className='border-b-12 pb-24 border-b-grey-dark'>
            <p className='font-grey leading-none mb-0 pb-0 text-4xl mt-0 pt-0'>The</p>
            <h1 className='mt-0  mb-0  pb-0 font-extrabold text-6xl 2xl:text-[6rem] text-grey-dark leading-none tracking-tighter '>
              Nebraska Creative
            </h1>

            <p className='leading-tight text-4xl mt-0 pt-0'>
              is your go-to resource for discovering <br />
              <span className='text-grey-dark font-bold italic'>design</span>,{' '}
              <span className='text-grey-dark font-bold italic'>advertising</span>, and{' '}
              <span className='text-grey-dark font-bold italic'>creative agencies</span>
              <br /> in the heart of the Midwest – aka good ol’ Nebraska.
            </p>
            <p className='text-2xl mt-12'>
              With the mindset of collaboration over competition, The Nebraska Creative embraces a
              diverse range of creative shops to showcase the assets and skills each has to offer –
              helping you find the perfect team of individuals ready to refresh your business and
              bring new ideas to life.
            </p>
          </div>
        </Section>
      </Main>
    </div>
  )
}
